// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadBookmarks() {
  return window['go']['main']['App']['LoadBookmarks']();
}

export function SaveToJSON(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveToJSON'](arg1, arg2, arg3);
}
